### PR TITLE
Pixi

### PR DESCRIPTION
**Pull request by sherpal**
The merge proposition is to add the example for using the Pixi.js library with ScalablyTyped.

Some of the examples from the official website are translated, the remaining ones should be pretty straightforward to adapt with the examples present here.

The readme within the Pixi directory contains some more information about the project. The remark regarding ScalablyTyped not handling parenthesis in enums should be removed when that issue is solved.

(The project also uses highlight.js but this is left silent in the readme, since it is not the main focus).

### CODE REVIEW

**Comment by oyvindberg** [comment]
Awesome, thanks! I have patches for the bugs you saw and will release a new version of the plugin within a few days. Will have a closer look at this also within a few days

**Comment by oyvindberg** [comment]
By the way I tested this locally and it seemed to work. stellar job @sherpal :)

The next beta release will still take a few more days, but I'll merge this as soon as possible

**Comment by sherpal** [comment]
Good news, thanks!

**Comment by oyvindberg** [comment]
I noticed a two of the demos are not working. I guess they were working when you submitted? Tested in firefox and chromium

Uniform:
```
pixi-opt-bundle.js:24 Uncaught TypeError: Cannot read property 'replace' of undefined
    at pixi-opt-bundle.js:24
    at t.createSyncGroups (pixi-opt-bundle.js:24)
    at t.syncUniforms (pixi-opt-bundle.js:24)
    at t.syncUniformGroup (pixi-opt-bundle.js:24)
    at t.bind (pixi-opt-bundle.js:24)
    at t._renderDefault (pixi-opt-bundle.js:165)
    at t._render (pixi-opt-bundle.js:165)
    at t.render (pixi-opt-bundle.js:40)
    at t.render (pixi-opt-bundle.js:40)
    at t.render (pixi-opt-bundle.js:24)
```

And Video never starts

Do you have any suggestions @sherpal ?

**Comment by sherpal** [comment]
The failure in the uniform example is weird. Possibly some js package is missing. I'll double check whether all dependencies are there.

For the Video, have you changed the asset provided in the repo with the actual asset from pixi? Because it's not an actual video, simply the same image file where I changed the extension (otherwise if it can't find the asset, it doesn't compile). Perhaps it would still be better to be an actual video. I always fear copyright issues when I embed stuff in github repos...

EDIT: I re-run with the demo as in the repo, and indeed that seems to be the issue, although I don't understand why we get this image since I replaced the jpg from the pixi example by an other jpg (the Scala logo, as for all other images)

**Comment by oyvindberg** [comment]
Doh, I hadn't seen/remembered the comment in the readme file about assets. I'll update the build file to do it automatically.

**Comment by oyvindberg** [comment]
I copied the assets into the repo in https://github.com/ScalablyTyped/Demos/commit/e8ee9bd62bf0f3a025e315fdda22a76a61e22610, even with an automatic solution for downloading them they would be checked into the repo inside the docs folder.

**Pull request merged**
